"""PDF generation helpers using ReportLab.

We keep layouts clean and minimal for MVP.
All fields are auto-filled from database models.

NOTE:
- For non-Latin scripts, register a suitable font.
"""

# Import reportlab for PDF creation
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# Import models for type hints
from app.db.models import User, Product, Shipment


def _draw_header(c: canvas.Canvas, title: str) -> None:
    """Draw a simple header."""

    # Header font
    c.setFont("Helvetica-Bold", 16)

    # Title
    c.drawString(40, 800, title)

    # Divider
    c.line(40, 790, 555, 790)


def generate_invoice_pdf(path: str, user: User, product: Product, shipment: Shipment) -> None:
    """Generate a commercial invoice PDF."""

    # Create canvas
    c = canvas.Canvas(path, pagesize=A4)

    # Header
    _draw_header(c, "Commercial Invoice")

    # Body font
    c.setFont("Helvetica", 11)

    # Exporter details
    c.drawString(40, 760, f"Exporter: {user.name or 'N/A'}")
    c.drawString(40, 745, f"Phone: {user.phone_number}")
    c.drawString(40, 730, f"IEC: {user.iec_number or 'Pending'}")

    # Product details
    c.drawString(40, 705, f"Product: {product.name}")
    c.drawString(40, 690, f"HS Code: {product.hs_code or 'Pending'}")
    c.drawString(40, 675, f"Declared Value: {product.declared_value:.2f} {product.currency}")

    # Shipment details
    c.drawString(40, 650, f"Destination: {shipment.destination_country}")
    c.drawString(40, 635, f"Courier: {shipment.courier} ({shipment.service_type})")
    c.drawString(40, 620, f"Incoterm: {shipment.incoterm}")

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, 80, "Auto-generated by Export OS MVP")

    # Finish
    c.showPage()
    c.save()


def generate_packing_list_pdf(path: str, user: User, product: Product, shipment: Shipment) -> None:
    """Generate a packing list PDF."""

    # Create canvas
    c = canvas.Canvas(path, pagesize=A4)

    # Header
    _draw_header(c, "Packing List")

    # Body font
    c.setFont("Helvetica", 11)

    # Packing details
    c.drawString(40, 760, f"Product: {product.name}")
    c.drawString(40, 745, f"Weight (kg): {product.weight_kg or 'Pending'}")
    c.drawString(
        40,
        730,
        f"Dimensions (cm): {product.length_cm or '?'} x {product.width_cm or '?'} x {product.height_cm or '?'}",
    )

    # Shipment reference
    c.drawString(40, 705, f"Pickup Address: {shipment.pickup_address}")
    c.drawString(40, 690, f"Tracking #: {shipment.tracking_number or 'Pending'}")

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, 80, "Auto-generated by Export OS MVP")

    # Finish
    c.showPage()
    c.save()


def generate_label_pdf(path: str, user: User, product: Product, shipment: Shipment) -> None:
    """Generate a simple shipping label PDF."""

    # Create canvas
    c = canvas.Canvas(path, pagesize=A4)

    # Header
    _draw_header(c, "Shipping Label")

    # Body font
    c.setFont("Helvetica", 12)

    # From
    c.drawString(40, 760, f"FROM: {user.name or 'Exporter'}")
    c.drawString(40, 740, f"Pickup: {shipment.pickup_address}")

    # To
    c.drawString(40, 700, "TO: Importer (UAE)")
    c.drawString(40, 680, "Address: [To be provided by buyer]")

    # Courier
    c.drawString(40, 640, f"Courier: {shipment.courier}")
    c.drawString(40, 620, f"Tracking: {shipment.tracking_number or 'Pending'}")

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, 80, "Auto-generated by Export OS MVP")

    # Finish
    c.showPage()
    c.save()
